Sammysteiner/issue 360 alert
HHS/grants-equity pull request #366
Opened 2023-07-28 18:11 UTC by SammySteiner

## Summary
Fixes #360 

### Time to review: 30 min

## Changes proposed

- Alert component 
- Alert has been added to index page
- Alert has it's own story
- Alert has it's own test and is tested on the index page

## Context for reviewers
- I'm assuming the Title section with "Home" will be replaced with the Hero component
- The mobile content for the alert in figma is different than the desktop content, I'm assuming that was an artifact of content changes, because the mobile content is longer. 🤷  But let me know if we want to accomodate different content for that piece based on screen size.

## Additional information
### Index page:
#### Desktop:
![image](https://github.com/HHS/grants-equity/assets/25465464/d044c9f7-9063-4283-ab93-1df5746781de)

#### Mobile:
![image](https://github.com/HHS/grants-equity/assets/25465464/da1c6eda-59ed-464e-9f47-4beba1ce8002)

### Storybook:
#### Docs
![image](https://github.com/HHS/grants-equity/assets/25465464/1b1fa055-4f53-4a0f-8703-20e6a117a248)

#### Single Story:
![image](https://github.com/HHS/grants-equity/assets/25465464/544e8c63-9db7-41a1-a705-861a5c2e34c2)

2023-07-28 20:08 UTC, daphnegold approved these changes
🚢 :shipit: 

This is so great! Awesome!@#$ 

The only thing I have to say that might warrant a teeny bit of consideration before merging is that the dropped in Alert component from USWDS has a colored line on the left side of the Alert. I personally think it looks fantastic, but it's not in the designs. So just a thought!

2023-07-28 20:08 UTC, daphnegold commented on frontend/src/components/Alert.tsx
> +    <USWDSAlert type={type} headingLevel="h4" slim>
My first time working USWDS design library, and it's turning out to be awesome. Love we can just drop this in.

2023-08-01 15:30 UTC, SammySteiner commented
> The only thing I have to say that might warrant a teeny bit of consideration before merging is that the dropped in Alert component from USWDS has a colored line on the left side of the Alert. I personally think it looks fantastic, but it's not in the designs. So just a thought!

Good catch! Based on your comment, I took a look at the truss USWDS React framework, as well as the USWDS design library, and the vertical line thing is hard coded into the design. Meaning, we'd have to write some custom Sass overrides to get rid of it. Based on that, I'm hoping it was just an oversight by Andy, and if he wants it removed, we can separate that off into its own ticket when he gets back.

2023-08-01 16:51 UTC, acouch requested changes
Looks great! This is my first time jumping in, similarly excited as @daphnegold .

Only issue I noticed is the icons not loading:

![image](https://github.com/HHS/grants-equity/assets/512243/43508102-0472-49f4-ab43-551fef46a90f)

2023-08-01 17:20 UTC, acouch commented
I tried to contribute a quick fix to the link on the index and broke the lint tests.

2023-08-01 19:04 UTC, SammySteiner commented
> Looks great! This is my first time jumping in, similarly excited as @daphnegold .
> 
> Only issue I noticed is the icons not loading:
@acouch I'm not seeing that issue, and I tried running with docker using `make dev` as well as locally with `npm run dev`. Want to pair to see if we can figure out why it's not working on your machine?
@daphnegold did you see that issue with the logo not loading?

2023-08-01 20:30 UTC, acouch approved these changes

2023-08-01 20:30 UTC, merged

2023-08-01 20:31 UTC, acouch commented
We discovered locally that there was another container of the same name, so the library wasn't downloaded.